#!/bin/bash
system=`uname -s`

case $system in 
Linux)
	echo "this is Linux system"
	;;
AUX)
	echo "This is AUX system"
	;;
Sunos)
	;;
esac




you=$LOGNAME
hour=$(date +%H)
echo "hour ===$hour"
echo "The time is $(date +%T) "
case $hour in
12)
	echo "Lunch time"
	;;
1[3-6])
	echo "good afternoon "
	;;
*)
	echo "good night"
	;;
esac
